---
title: Exploratory Data Analysis
format: typst
---

### Question 1

Which district was the closest race?

### Answer 1

```{r}
dist_votes <- cleaned_vr_dist_lvl |>
    filter(toupper(party) %in% c("DEM", "REP")) |>
    group_by(district, party) |>
    summarize(total_votes = sum(votes, na.rm = T)) |>
    ungroup()

dist_votes |>
pivot_wider(names_from = party, values_from = total_votes, values_fill = 0) |>
mutate(margin = abs(DEM-REP))

dist_votes$district
```

### Question 2

What parties received the most votes?

### Answer 2

```{r}
dist_votes |>
    group_by(party) |>
    summarize(total = sum(total_votes, na.rm = TRUE)) |>
    arrange(desc(total)) |>
    slice_max(total) |>
    pull(party)
```

### Question 3

What is the difference between registered voters versus actual voter turnout?

### Answer 3

```{r}
reg_vs_turnout <- cleaned_vr_precint_lvl |>
    mutate(
        difference = TOTREG - TOTVOTE,
        turnout_rate = TOTVOTE / TOTREG
  )

reg_vs_turnout[, c("difference", "turnout_rate")] |>
    slice(1)
```